### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by huseyinduz** [opportus/service-pack-for-storefront#5]
I use free version storefront 

Warning: ucwords() expects exactly 1 parameter, 2 given in /var/www/wp-content/plugins/service-pack-for-storefront/class-spfs.php on line 129

Fatal error: Class 'SPFS_' not found in /var/www/wp-content/plugins/service-pack-for-storefront/class-spfs.php on line 131

thank you

**Comment by opportus** [comment]
Hi @huseyinduz Thank you for reporting this bug.

Could you confirm what's your PHP version?
I just found out that the second parameter of ucwords have been added in PHP version 5.4.32, 5.5.16
Source: http://php.net/manual/fr/function.ucwords.php#refsect1-function.ucwords-changelog

**Comment by huseyinduz** [comment]
thank you @opportus 
yes upgrade php version 5.5.9 to 5.5.37 install ok

**Comment by opportus** [comment]
@huseyinduz, that's also what I would do on your place.

Anyway, I made a fix for PHP versions lower than 5.5.17
I'm going to push the commit soon to WordPress and GitHub.
Don't hesistate to let me know if you find new bugs since I didn't test also on PHP 5.5.37...
Thank you !

**Comment by opportus** [comment]
Fixed
