### ISSUE TITLE
Invalid / Missing tracking number or tracking shipper.

### ISSUE THREAD

**Issue by mikekosulin** [opportus/service-pack-for-storefront#6]
Trying to add custom tracks with url like:
http://www.edostavka.ru/track.html?order_id=
or
https://www.pochta.ru/tracking#

but get error after adding track num to order: Invalid / Missing tracking number or tracking shipper.

**Comment by opportus** [comment]
Hi @mikekosulin 
I'd need more info... Can you confirm you did select the shipper name in the meta box just upon the tracking number field ?

**Comment by mikekosulin** [comment]
I think, there are problems with Cyrillic delivery-name.
With latin - works.

**Comment by opportus** [comment]
I see, it makes sense then.

The problem is that a Cyrilic name won't pass the data validation which will trigger the error message.
I'm going to fix it asap, tomorrow, I will push the new release which will contain the fix to your issue.

Thanks for having pointed this issue.

**Comment by opportus** [comment]
Fixed.
